name: datalab-stack
domain: example.com
stage: dev
provider:
  name: aws
  region: us-east-1
stack:
  web:
    deployment:
      image: 'wrn::datalab-app'
      version: 0.0.1
  backend:
    deployment:
      image: 'wrn::datalab-backend'
      version: 0.0.1
  dl-messaging-google-mail-service:
    deployment:
      image: 'wrn::dl-messaging-google-mail-service'
      version: 0.0.1
  dl-tasks-asana-service:
    deployment:
      image: 'wrn::dl-tasks-asana-service'
      version: 0.0.1
  dl-messaging-hotmail-service:
    deployment:
      image: 'wrn::dl-messaging-hotmail-service'
      version: 0.0.1
  dl-orgs-contacts-service:
    deployment:
      image: 'wrn::dl-orgs-contacts-service'
      version: 0.0.1
  wireline.io/store:
    reference:
      endpointUrl: wrn::wireline.io/wireline/store
