name: datalab-stack
domain: tinchoz49
stage: dev
provider:
  name: aws
  region: us-east-1
stack:
  web:
    deployment:
      image: 'wrn::datalab-app'
      version: 0.0.1
  backend:
    deployment:
      image: 'wrn::datalab-backend'
      version: 0.0.1
