name: datalab-stack
domain: example.com
stage: prod
provider:
  name: aws
  region: us-east-1
stack:
  web:
    deployment:
      image: 'wrn::datalab-app'
      version: 0.0.1
      environment:
        WRL_PUBLIC_PATH: /prod
  backend:
    deployment:
      image: 'wrn::datalab-backend'
      version: 0.0.1
  dl-orgs-contacts-service:
    deployment:
      image: 'wrn::dl-orgs-contacts-service'
      version: 0.0.1
  dl-spellcheck-alex-service:
    deployment:
      image: 'wrn::dl-spellcheck-alex-service'
      version: 0.0.1
  wireline.io/store:
    reference:
      endpointUrl: wrn::wireline.io/wireline/store
