name: datalab-contacts
platform: nodejs
buildTool: yarn
version: 0.0.1
functions:
  gql:
    handler: handler.gql
    description: '{ "interface": "wire://datalab/contacts" }'
    events:
      - http:
          path: gql
          method: post
          cors: true
