name: datalab-backend
platform: nodejs
buildTool: yarn
version: 0.0.1
functions:
  gql:
    handler: handler.gql
    description: GraphQL Endpoint
    events:
      - http:
          path: gql
          method: post
          cors: true
  reset:
    handler: handler.reset
    description: Reset the storage.
    events:
      - http:
          path: reset
          method: get
          cors: true
