name: dl-messaging-hotmail-stack
domain: tinchoz49
stage: dev
provider:
  name: aws
  region: us-east-1
stack:
  gql:
    deployment:
      image: 'wrn::dl-messaging-hotmail-service'
      version: 0.0.1
