name: datalab-contacts
domain: example.com
stage: dev
provider:
  name: aws
  region: us-east-1
stack:
  gql:
    deployment:
      image: 'wrn::datalab-contacts'
      version: 0.0.1
  wireline.io/store:
    reference:
      endpointUrl: wrn::wireline.io/wireline/store
