name: dl-orgs-contacts-stack
domain: example.com
stage: dev
provider:
  name: aws
  region: us-east-1
stack:
  gql:
    deployment:
      image: 'wrn::dl-orgs-contacts-service'
      version: 0.0.1
  wireline.io/store:
    reference:
      endpointUrl: wrn::wireline.io/wireline/store
