name: dl-messaging-google-mail-stack
domain: example.com
stage: dev
provider:
  name: aws
  region: us-east-1
stack:
  gql:
    deployment:
      image: 'wrn::dl-messaging-google-mail-service'
      version: 0.0.1
