name: datalab-spellcheck
platform: nodejs
buildTool: yarn
version: 0.0.1
functions:
  gql:
    handler: handler.gql
    description: "{ interface: 'wire://datalab' }"
    events:
      - http:
          path: gql
          method: post
          cors: true
