name: datalab-stack
domain: tel.example.com
stage: dev
provider:
  name: openfaas
  region: us-east-1
stack:
  web:
    deployment:
      image: 'wrn::datalab-app'
      version: 0.0.1
  backend:
    deployment:
      image: 'wrn::datalab-backend'
      version: 0.0.1
      environment:
        WRL_ALLOW_DEMOCREDENTIALS: "0"
  datalab-spellcheck:
    deployment:
      image: 'wrn::datalab-spellcheck'
      version: 0.0.1
  datalab-contacts:
    deployment:
      image: 'wrn::datalab-contacts'
      version: 0.0.1
  wireline.io/store:
    reference:
      endpointUrl: wrn::wireline.io/wireline/store
